export const ACTIONS = {
  NOTIFY: 'NOTIFY',
  AUTH: 'AUTH',
  SIDE_MENU_TOGGLE: 'SIDE_MENU_TOGGLE',
  SIDE_MENU_CLOSE: 'SIDE_MENU_CLOSE',
  SIDE_MENU_TURN_ON: 'SIDE_MENU_TURN_ON',
  RESET_SCROLL: 'RESET_SCROLL',
  IT_IS_BURGER: 'IT_IS_BURGER_COMPONENT',
  LOADING_ON: 'LOADING_ON',
  LOADING_OFF: 'LOADING_OFF',
}

export default ACTIONS
